/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, middleware, at https://www.jitblox.com/project/RwZp7SqKfr
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbCollapseModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-sidenav',
  standalone: true,
  templateUrl: './sidenav.component.html',
  styleUrls: ['./sidenav.component.scss'],
  imports: [NgbCollapseModule, RouterLink, CommonModule]
})
export class SidenavComponent {

  constructor() {}

  public onButton1Click($event: MouseEvent): void {
    $event.preventDefault();
  }

  public onButton2Click($event: MouseEvent): void {
    $event.preventDefault();
  }

  public onButton3Click($event: MouseEvent): void {
    $event.preventDefault();
  }

  public onButton4Click($event: MouseEvent): void {
    $event.preventDefault();
  }
}
