/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, middleware, at https://www.jitblox.com/project/RwZp7SqKfr
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-tomcat',
  standalone: true,
  templateUrl: './tomcat.component.html',
  styleUrls: ['./tomcat.component.scss'],
  imports: [NgbDropdownModule, CommonModule]
})
export class TomcatComponent {

  constructor() {}
}
