/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, middleware, at https://www.jitblox.com/project/RwZp7SqKfr
*/

import { Routes } from '@angular/router';
import { TomcatComponent } from './components/modules/InstanceManagement/tomcat.component';

export const routes: Routes = [
  {
    path: 'tomcat',
    component: TomcatComponent
  }
];
