/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, middleware, at https://www.jitblox.com/project/RwZp7SqKfr
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { HomeComponent } from './components/modules/home.component';
import { FooterComponent } from './components/modules/shared/footer.component';
import { HeaderComponent } from './components/modules/shared/header.component';
import { SidenavComponent } from './components/modules/shared/sidenav.component';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  imports: [HeaderComponent, SidenavComponent, HomeComponent, FooterComponent, CommonModule]
})
export class AppComponent {

  constructor() {}
}
